FROM php:8.1-fpm
# Install Libs
RUN apt-get update \
    && apt-get install -y \
    libmagickwand-dev --no-install-recommends \
    zip \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libmemcached-dev \
    libpng-dev \
    libicu-dev \
    libpq-dev \
    libzip-dev \
    wget \
    git-all \
    ghostscript \
    pdftk \
    exif \
    && rm -rf /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-jpeg --with-freetype \
    && docker-php-ext-install gd \
    && docker-php-ext-install zip \
    && docker-php-ext-install pcntl
# Install specific lib wkhtmltopdf for pdf printer
RUN apt-get update && apt-get install -y -q --no-install-recommends \
    build-essential \
    libfontconfig1-dev \
    libfreetype6-dev \
    libpng-dev \
    libx11-dev \
    libxext-dev \
    libxrender-dev \
    python \
    zlib1g-dev \
    xfonts-75dpi \
    xfonts-base \
# Install Extensions
RUN docker-php-ext-configure intl \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install -j$(nproc) pdo pdo_pgsql soap bcmath zip intl \
    && pecl install xdebug mcrypt-1.0.5\
    && docker-php-ext-enable xdebug mcrypt \
    && docker-php-ext-install calendar \
    && docker-php-ext-configure calendar \
    ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && install-php-extensions mbstring exif
# Configure XDebug
RUN echo "xdebug.mode=debug"  >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.client_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_handler=dbgp" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.discover_client_host=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo 'xdebug.idekey="PHPSTORM"' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/bin/composer
#Install Locales
RUN apt-get update
RUN apt-get -y install locales
RUN sed -i '/fr_FR.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen
ENV LANG fr_FR.UTF-8
ENV LANGUAGE fr_FR:fr
ENV LC_ALL fr_FR.UTF-8
ENV LC_CTYPE fr_FR.UTF-8
# File mode trick -> use dev logged user id
RUN usermod -u 1000 www-data
WORKDIR /var/www
USER www-data
CMD ["php-fpm"]
EXPOSE 9000
